# Generated by Django 5.1.1 on 2024-11-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
