# Generated by Django 5.1.1 on 2024-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_admin_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_registration',
            name='Confirm_Password',
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='Aadhar',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='Age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='Experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='LicenseImage',
            field=models.ImageField(null=True, upload_to='License'),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driver_registration',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver_registration',
            name='image',
            field=models.ImageField(null=True, upload_to='dpimg'),
        ),
    ]
