# Generated by Django 5.1.1 on 2024-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_vehicle_rental_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_registration',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='license_image',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='owner_image',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rental_registration',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='LicenseImage',
            field=models.ImageField(null=True, upload_to='License'),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Roles',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='image',
            field=models.ImageField(null=True, upload_to='dpimg'),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Aadhar',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rental_registration',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
